### ISSUE TITLE
Compile without sqlite: database abstraction for something like `.gob`

### ISSUE THREAD

**Issue by mro** [adtac/commento#167] opened 2018-03-28 20:41 UTC
I'm wondering if sqlite helps more than it blocks here. It IMO requires cgo which make cross-compilation and cross-platform availability much more pain. And we're talking self-hosting load rather than wp.com.

Did you consider primitive `.gob` persistence?

**Comment by adtac** [comment] 2018-03-29 05:45
Hmm, good suggestion. We already have support for database abstraction (but sqlite is the only implemented DB, however; others should be trivial). But honestly, our current implementation of this abstraction won't actually help your case as sqlite is still compiled into the binary.

If you want to be completely rid of sqlite, there has to be some sort of conditional compilation [1]. Maybe someone with more Go experience can comment on what the best way to do this might be.

Thanks for creating this issue! It's a really interesting problem to solve.

[1] Apparently Go does not have a preprocessor/macro system. But https://stackoverflow.com/questions/38950909/c-style-conditional-compilation-in-golang comes close enough.

**Comment by mro** [comment] 2018-03-29 17:13
I'm rolling a radical experiment over at https://github.com/mro/ShaarliGo and do fine with 5k posts so far in a xml file (which is 10x slower I/O than gob).

So, dependant on the intended use-cases and quantity structure, there may not be a need for a db at all?

What are the numbers of posts/users/comments you target?

**Comment by adtac** [comment] 2018-06-11 13:19
@mro Thanks a lot for this issue! The new version of Commento only supports PostgreSQL (by design; supporting and maintaining multiple databases is too much effort until someone comes up with a really amazing abstraction). Moving to *just* PostgreSQL as its advantages over an ORM: ORMs won't give you the level of configuration that postgres does. For example, we make of postgres specific features like insert/delete triggers for voting, etc.

Anyway, my point is, I think this issue is only valid for the older, deprecated version.

BTW, we've moved all development [to GitLab](https://gitlab.com/commento/commento-ce). So I'm closing this issue. Cheers, and good luck with ShaarliGo!

**Closed by adtac** 2018-06-11 13:19 UTC
Labels: area/backend, status/help wanted, status/needs design
