### ISSUE TITLE
CSS Selector for all styles

### ISSUE THREAD

**Issue by kWeb24** [adtac/commento#58] opened 2017-05-02 14:20 UTC
For example **#commento** selector. Now JS adds styles in the end of header section so Commento and Spectre styles will override existing styles.

That means the fastest redesign you've ever made to your website but it's usually bad for it. ;)

**Comment by DarkThrone** [comment] 2017-05-03 02:12
Setting aside that if you have two nodes with the same ID you have a different problem. Yes, we need to namespace Commento. I'll probably work on this later on the week, I plan to remove the spectre dependency at all.

**Comment by adtac** [comment] 2017-05-03 06:58
namespace the Commento CSS?

And how are we removing spectre? It's a nice library :) Or do you mean copying just the essential elements and putting them in the namespace?

**Comment by DarkThrone** [comment] 2017-05-03 09:18
@adtac Commento use case is relatively simple and we don't need the whole spectre file. We can just port over the styles that we need, and remove the rest. Maintenance will be way easier. 

About the namespacing, yes, we need to namespace Commento styles, otherwise it will break on different sites.

**Comment by kWeb24** [comment] 2017-05-04 16:18
@adtac We've got commento wrapper wich is a div with #commento ID. That will be enough, there's only 1 instance of Commento per post page anyway.

And yeah, Spectre is overkill here, good choice with removing it.

**Comment by adtac** [comment] 2017-11-14 19:04
Moved the whole thing from spectre to a custom styling CSS. It looks much better now :) Check it out.

**Comment by kWeb24** [comment] 2017-11-16 14:24
@adtac Looks better now but there's still styles for elements like 'a' wich will interfere with the template styles i think. This should not be a problem if these styles are above template styles (so the template overrides them) but here the commento.css seems to still be added by js at the bottom of the head section.

I have not tested it yet, I will look into it later and let you know.

**Comment by adtac** [comment] 2017-11-16 14:50
Yeah, that's why I didn't close the issue.

The problem is more difficult than it seems: since we're using showdown for markdown rendering, adding a class to links will be a little more work. We'll probably need to fork showdown (or a similar markdown library) and make changes (provided the license allows for merging the changes in as MIT).

This would also give us more control over what markdown element are allowed vs what isn't. Stuff like headings shouldn't really be in a comment; basic text stuff like links, bold, italics, strikethrough, bullet points, images (not sure about the last one) should be sufficient.

**Comment by kWeb24** [comment] 2017-11-16 17:42
What about mentioned before #commento wrapper? I don't know showdown but styling within the #commento selector should not affect the markdown. 

Simple solution, and that's how I solved my problem when I added the issue.

**Comment by adtac** [comment] 2017-11-17 05:45
Wow, I didn't know you could do: (Clearly, I'm not very good at CSS :P)

```css
#commento a {
    ...
}
```

That should solve our problems entirely :)

**Comment by adtac** [comment] 2017-11-17 05:46
I'll make a patch this weekend.

**Comment by kWeb24** [comment] 2017-11-17 11:46
Knowledge +1 :)

**Closed** 2017-11-18 11:49 UTC
Labels: area/frontend, difficulty/high, type/bug

**Comment by adtac** [comment] 2017-11-18 11:51
Solved with https://github.com/adtac/commento/commit/25e304cd124f4a0214b3cf27d3c1cd24237be5d9

Here's what it looks like now:

![img](https://user-images.githubusercontent.com/7521600/32979991-ce7c670e-cc84-11e7-8c9c-f7209864006a.png)

As you can see, the Lorem Ipsum part (and the link part) are not styled by commento (it should be sans-serif), but the comments are :)
