### ISSUE TITLE
Remove unnecessary sql.Tx in createComment

### ISSUE THREAD

**Issue by peteretelej** [adtac/commento#31] opened 2017-04-27 16:38 UTC
The transaction started and committed in `createComment` is unncessary, as the `db.Exec` suffices and does not use it.

Instead of
``` go
func createComment(url string, name string, comment string, parent int) error {
	tx, err := db.Begin()
	if err != nil {
		return err
	}

	statement := `
		INSERT INTO comments(url, name, comment, time, parent) VALUES(?, ?, ?, ?, ?);
	`
	_, err = db.Exec(statement, url, name, comment, time.Now(), parent)
	if err != nil {
		return err
	}

	return tx.Commit()
}

```

it just needs

``` go
func createComment(url string, name string, comment string, parent int) error {
	statement := `
		INSERT INTO comments(url, name, comment, time, parent) VALUES(?, ?, ?, ?, ?);
	`
	_, err = db.Exec(statement, url, name, comment, time.Now(), parent)
	if err != nil {
		return err
	}
}

```

**Comment by adtac** [comment] 2017-04-28 13:01
Dupe of https://github.com/adtac/commento/issues/10 but yours is more verbose. Closing that one in favor of this.

**Closed** 2017-04-28 15:54 UTC
