### ISSUE TITLE
Symbols in code blocks converted to HTML entities

### ISSUE THREAD

**Issue by elamperti** [adtac/commento#40] opened 2017-04-29 13:37 UTC
I wrote a test comment with a code block (using ` ```sh `) and `echo "hi"` was converted to `echo &#34;hi&#34;`. That shouldn't happen! :fearful:

Reference screenshot:
![selection_011](https://cloud.githubusercontent.com/assets/910672/25555875/bdb946ec-2cc7-11e7-9766-a26824c7364a.jpg)

**Comment by DarkThrone** [comment] 2017-04-30 00:39
I believe I know where the problem is. You can leave this one to me @adtac if you'd like.

**Comment by acz13** [comment] 2017-04-30 01:11
...just don't escape inside `<pre>`?

**Comment by DarkThrone** [comment] 2017-04-30 02:18
@acz13 showdown always escapes entities inside `<pre><code>`. This is due to a double encoding that happens in `http.go` when we `HTMLEscapeString`. I think the solution is to sanitise the output string looking for double encodings before displaying anything.

**Comment by adtac** [comment] 2017-04-30 06:59
Yep, that's the issue.

@DarkThrone I can't assign you (or anyone else) for some reason using the Github UI. But consider yourself assigned ;)

**Comment by adtac** [comment] 2018-06-11 12:18
@rrggrr @klebervirgilio @captncraig @cweagans This feature has now been implemented! In the latest version of Commento (basically a rewrite), you now have the option to require all comments to go through moderation.

@elamperti @acz13 @DarkThrone This bug has been fixed in the latest version of Commento (basically a rewrite).

BTW, we've moved all development [to GitLab](https://gitlab.com/commento/commento-ce). So I'm closing this issue for two reasons: the bug has been fixed, and all issues are now being moved to GitLab. Cheers!

**Closed by adtac** 2018-06-11 12:18 UTC
Labels: area/frontend, difficulty/medium, type/bug
